ignore:
- "hack"
- "vendor"
- "**/zz_generated*.go"
- "docs"
- "pkg/apis/knative/serving/v1"
- "pkg/apis/cartographer/v1alpha1/cluster_supply_chain.go"
- "pkg/apis/cartographer/v1alpha1/workload.go"
- "pkg/apis/cartographer/v1alpha1/zz_generated.deepcopy.go"
- "pkg/dies"
- "pkg/cli-runtime/survey.go"
- "pkg/cli-runtime/testing"
- "pkg/commands/docs.go"
comment:
  # Update existing comment or create new if deleted.
  behavior: default
