//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 VMware, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	metav1 "dies.dev/apis/meta/v1"
	json "encoding/json"
	fmtx "fmt"
	servingv1 "github.com/vmware-tanzu/apps-cli-plugin/pkg/apis/knative/serving/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

var ServiceBlank = (&ServiceDie{}).DieFeed(servingv1.Service{})

type ServiceDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       servingv1.Service
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceDie) DieImmutable(immutable bool) *ServiceDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceDie) DieFeed(r servingv1.Service) *ServiceDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ServiceDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceDie) DieFeedPtr(r *servingv1.Service) *ServiceDie {
	if r == nil {
		r = &servingv1.Service{}
	}
	return d.DieFeed(*r)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceDie) DieRelease() servingv1.Service {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceDie) DieReleasePtr() *servingv1.Service {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object.
func (d *ServiceDie) DieReleaseUnstructured() runtime.Unstructured {
	r := d.DieReleasePtr()
	u, _ := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceDie) DieStamp(fn func(r *servingv1.Service)) *ServiceDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceDie) DeepCopy() *ServiceDie {
	r := *d.r.DeepCopy()
	return &ServiceDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*ServiceDie)(nil)

func (d *ServiceDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ServiceDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ServiceDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ServiceDie) UnmarshalJSON(b []byte) error {
	if d == ServiceBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &servingv1.Service{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ServiceDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *ServiceDie {
	return d.DieStamp(func(r *servingv1.Service) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *ServiceDie) StatusDie(fn func(d *ServiceStatusDie)) *ServiceDie {
	return d.DieStamp(func(r *servingv1.Service) {
		d := ServiceStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *ServiceDie) Status(v servingv1.ServiceStatus) *ServiceDie {
	return d.DieStamp(func(r *servingv1.Service) {
		r.Status = v
	})
}

var ServiceStatusBlank = (&ServiceStatusDie{}).DieFeed(servingv1.ServiceStatus{})

type ServiceStatusDie struct {
	mutable bool
	r       servingv1.ServiceStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceStatusDie) DieImmutable(immutable bool) *ServiceStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceStatusDie) DieFeed(r servingv1.ServiceStatus) *ServiceStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ServiceStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceStatusDie) DieFeedPtr(r *servingv1.ServiceStatus) *ServiceStatusDie {
	if r == nil {
		r = &servingv1.ServiceStatus{}
	}
	return d.DieFeed(*r)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceStatusDie) DieRelease() servingv1.ServiceStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceStatusDie) DieReleasePtr() *servingv1.ServiceStatus {
	r := d.DieRelease()
	return &r
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceStatusDie) DieStamp(fn func(r *servingv1.ServiceStatus)) *ServiceStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceStatusDie) DeepCopy() *ServiceStatusDie {
	r := *d.r.DeepCopy()
	return &ServiceStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ServiceStatusDie) Conditions(v ...apismetav1.Condition) *ServiceStatusDie {
	return d.DieStamp(func(r *servingv1.ServiceStatus) {
		r.Conditions = v
	})
}

// URL holds the url that will distribute traffic over the provided traffic targets. It generally has the form http[s]://{route-name}.{route-namespace}.{cluster-level-suffix}
func (d *ServiceStatusDie) URL(v string) *ServiceStatusDie {
	return d.DieStamp(func(r *servingv1.ServiceStatus) {
		r.URL = v
	})
}
